FROM python:3.10-slim
ENV PYTHONUNBUFFERED True

ARG MLFLOW_EXPERIMENT_NAME
ARG MLFLOW_TRACKING_USERNAME
ARG MLFLOW_TRACKING_PASSWORD
ARG MLFLOW_EXPERIMENT_TRACKING_URI
# ARG GCLOUD_ACCESS_TOKEN
ARG GCS_BUCKET_NAME
# ARG PROJECT_ID

ENV PYTHONUNBUFFERED=True

# ENV PROJECT_ID=$PROJECT_ID
# ENV GCLOUD_ACCESS_TOKEN=$GCLOUD_ACCESS_TOKEN
ENV GCS_BUCKET_NAME=$GCS_BUCKET_NAME
ENV MLFLOW_EXPERIMENT_NAME=$MLFLOW_EXPERIMENT_NAME
ENV MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME
ENV MLFLOW_TRACKING_PASSWORD=$MLFLOW_TRACKING_PASSWORD
ENV MLFLOW_EXPERIMENT_TRACKING_URI=$MLFLOW_EXPERIMENT_TRACKING_URI
WORKDIR /app
COPY ./serve-requirements.txt ./
COPY ./key.json ./

ENV GOOGLE_APPLICATION_CREDENTIALS="/app/key.json"
RUN pip install --no-cache-dir -r serve-requirements.txt
COPY ./serve ./serve
EXPOSE 8080
CMD ["uvicorn", "serve.api:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers"]
